
on:
  push:
    tags:
      - 'v*'
name: build and push docker image
jobs:
  deploy-production:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: docker login
      run: |
        echo ${{ secrets.GH_TOKEN_FOR_GHCR }} | docker login ghcr.io -u ainoya --password-stdin
    - name: docker build 
      run: |
        make build
    - name: docker push
      run: |
        make push_ghcr
