
on:
  push:
    branches:
      - master
name: build and push docker image
jobs:
  deploy-production:
    name: build and push docker image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - run: |
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: package version
      run: |
        make update_minor_version
        git push origin --tags
    - name: docker login
      run: |
        echo ${GITHUB_TOKEN} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: docker build 
      run: |
        make build
    - name: docker push
      run: |
        make push_ghcr
